// JavaScript Document
modspecs = [


{ 
	partNo:  "GRV-IMA-24",
	features: {
	
		"Analog totalizing" : true,
		"Watchdog timer" : false,
		"Minimum/maximum values" : true,
		"Offset and gain" : true,
		"Average filter weight" : true,
		"Quality Indicator" : true,
		
		"Number of Channels": 24,
	},
	specifications: {
	  "Input Range (per channel)": "-20 to +20 mA, 0 to 20 mA, 4 to 20 mA",
      "Over-range limits": "-22 mA to +22 mA",
      "Resolution": "0.02 µA (20-bits)",
      "Accuracy": "± 0.1% ( ± 20 µA )",
      "Gain Temperature Coefficient": "ppm/°C",
      "Offset Temperature Coefficient": "ppm/°C",
      "Input Voltage Drop nominal (Impedance ± 20%)": "5.5 V nominal @ 20 mA (275 Ohms)",
      "Input Filter (hardware)": "-3 dB at 140 Hz",
      "Step Input Response Time": "277 ms x SMA value (8.8 s @ 32 SMA, Default SMA = 4 )",
      "Data Freshness / Update": "277 ms",
      "Analog Data Filtering": "-3 dB @ 2.4 Hz / -25 dB @ 60 Hz",
      "Software Data Filtering, simple moving average (SMA) and Weighted Filter": "SMA: 1 to 32 Readings, Filter Weight: 1 to 4096",
      "AC/DC Common Mode Rejection": "> -120 dB",
      "Max. Survivable Input": "± 32 V",
      "Max. Operating Common Mode Voltage": "250 V",
      "Problem Indications": "out of range",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "300V between zone A (ch 0–11) & zone B (ch 12–23)",
      "Chassis Power Consumption": "1.0 W",
	  "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
	  "Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
      
	}
},
{ 
	partNo:  "GRV-ITMI-8",
	features: {
		"Analog totalizing" : true,
		"Watchdog timer" : false,
		"Minimum/maximum values" : true,
		"Offset and gain" : true,
		"Average filter weight" : true,
		"Quality Indicator" : true,
		 "Number of Channels": 8,
	},
	specifications: {
	 "Millivolt Input Ranges": "±1200.0 mV, ±600.0 mV, ±300.0 mV, ±150.0 mV, ±75.0 mV, ±50.0 mV, ±25.0 mV",
      "Over range limits (± 10%)": "±1320.0 mV, ±660.0 mV, ±330.0 mV, ±165.0 mV, ±82.5 mV, ±55.0 mV, ±27.5 mV",
      "Resolution": "mV Range / 1,048,576  (20 bits)",
      "Accuracy 0.1% of Range": "±1200 µV, ±600 µV, ±300 µV, ±150 µV, ±75 µV, ±50 µV, ±50 µV",
      "Thermocouple ITS90 Types": "Accuracy* / Resolution",
      "B:   90 °C to 1,820 °C (194 °F to 3,308 °F)": "5.0 °C (9.0  °F)/  0.05 °C (0.1 °F)",
      "E: -270 °C to 1,000 °C (-454 °F to 1,832 °F)": "2.0 °C (3.6  °F)/ 0.05 °C (0.1 °F)",
      "J: -210 °C to 1,200 °C (-346 °F to 2,192 °F)": "2.0 °C (3.6  °F)/ 0.05 °C (0.1 °F)",
      "K: -270 °C to 1,372 °C (-454 °F to 2,501.6 °F)": "2.0 °C (3.6  °F)/ 0.05 °C (0.1 °F)",
      "N: -270 °C to 1,300 °C (-454 °F to 2,372 °F)": "3.0 °C (5.4  °F)/ 0.05 °C (0.1 °F)",
      "R:  -50 °C to 1,768 °C (-58 °F to 3,214.4 °F)": "5.0 °C (9.0  °F)/ 0.05 °C (0.1 °F)",
      "S:  -50 °C to 1,768 °C (-58 °F to 3,214.4 °F)": "5.0 °C (9.0  °F)/ 0.05 °C (0.1 °F)",
      "T: -270 °C to  400 °C (-454 °F to 752 °F)": "3.0 °C (5.4  °F)/ 0.05 °C (0.1 °F)",
      "Cold Junction Compensation": "Automatic",
      "Data Freshness (nominal)": "mV Ranges = 21 ms  /  T/C Ranges = 46 ms",
      "Analog Data Filtering": "-3 dB @ 2.4 Hz / -25 dB @ 60 Hz",
      "Software Data Filtering, simple moving average (SMA) and Weighted filter": "SMA (1 to 32 readings) and Filter Weight (1 to 4096)",
      "Step Response Time (to 1%)": "85 ms",
      "Common Mode Rejection": "> -120 dB AC/DC",
      "Input Resistance": "100 megohm",
      "Drift   Offset  /  Gain": "? / ?",
      "Problem Indication": "out of range, open thermocouple",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "300 V working, 1500 V transient (1 minute)",
      "Chassis Power Consumption": "1.4 W",
	   "Agency Approvals": "UL/cUL (Class 1 Div. 2); CE, ATEX (Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
		"Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Humidity (non-condensing)": "5–95% RH",
     
	},
},
{ 
	partNo:  "GRV-IV-24",
	features: {
		"Analog totalizing" : true,
		"Watchdog timer" : false,
		"Minimum/maximum values" : true,
		"Offset and gain" : true,
		"Average filter weight" : true,
		"Quality Indicator" : true,
		 "Number of Channels": 24,
	},
	specifications: {
	  "Input Ranges": "±160.0 VDC, ±80.0 VDC, ±40.0 VDC, ±20.0 VDC, ±10.0 VDC, ±5.0 VDC, ±2.5 VDC, ±1.25 VDC",
      "Over-range limits": "±176.0 VDC, ±88.0 VDC, ±44.0 VDC, ±22.0 VDC, ±11.0 VDC, ±5.5 VDC, ±2.75 VDC, ±1.375 VDC",
      "Resolution": "Range / 1,048,576 (20-bits)",
      "Accuracy 0.1% of Range": "±160 mV, ±80 mV, ±40 mV, ±20 mV, ±10 mV, ±5 mV, ±2.5 mV, ±1.25 mV",
      "Gain Temperature Coefficient": "ppm/°C",
      "Offset Temperature Coefficient": "ppm/°C",
      "Input Impedance Nominal": "9.7 MOhms",
      "Input Filter": "-3 dB at 460 HZ",
      "Software Data Filtering, SMA ( simple moving average) and Weighted filter (Original)": "1 to 32 Readings,  moving average and (Original) 1 to 4096 Filter Weight",
      "Step Input Response Time": "277 ms x SMA value (8.8 s @ 32 SMA, Default SMA = 4 )",
      "Data Freshness / Update": "277 ms",
      "Analog Data Filtering": "-3 dB @ 2.4 Hz / -25 dB @ 60 Hz",
      "DC Common Mode Rejection": "> -120 dB",
      "AC Common Mode Rejection": "> -120 dB",
      "Max. Survivable Input": "300 V",
      "Max. Operating Common Mode Voltage": "250 V",
      "Problem Indications": "out of range",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "300V Between Zone A (ch 0–11) & Zone B (ch12–23)",
      "Chassis Power Consumption": "1.0 W",
     "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
	  "Connector": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
	},
},
{ 
	partNo:  "GRV-OVMALC-8",
	features: {
		"Watchdog timer" : true,
		"Scaling" : false,
		"Minimum/maximum values" : false,
		"Offset and gain" : false,
		"Average filter weight" : false,
		"Quality Indicator" : true,
		"Clamping" : true,
		
	  "Number of Channels": 8,
	},
	specifications: {
	  "Output Ranges (Resolution)": "0 to 5 VDC  (1.22mV), 0 to 10 VDC  (2.44mV), -5 to +5 VDC  (2.44mV), -10 to +10 VDC  (4.88mV), 4 to 20 mA  (4µA), 0 to 20 mA  (5µA), 0 to 22 mA  (6µA)",
      "Resolution": "Range / 4096 (12-bits)",
      "Accuracy": "± 0.1% of span",
      "Output impedance": "280 Ohms",
      "Data Refresh Time": "10 ms",
      "Problem Indication": "Current outputs: Open circuit / Voltage outputs: Over-current",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "None",
      "Chassis Power Consumption": "1.8 W all voltage outputs / 6.2 W all current outputs",
	  "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
	  "Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
      
	},
},

{ 
	partNo:  "GRV-IAC-24",
	features: {
		"On/off state" : true,
		"On/off latching" : true,
		"Frequency measurement" : true,
		"Period measurement" : true,
		"Pulse measurement" : true,
		"Counting / Quadrature Counting" : true,
		"Output pulsing" : false,
		"On/off totalization" : true,
		"Channel-to-channel isolation": false,
		"Number of Channels": 24,

	},
	specifications: {
	"Nominal Input Voltage Range (RMS)": "85–140 VAC",
      "Turn-on Voltage": "85 VAC",
      "Turn-off Voltage": "35 VAC",
      "Input Impedance (± 5%)": "133 kOhms",
      "Operating Frequency": "40 Hz to 400 Hz",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "NONE",
      "Chassis Power Consumption": "1.0 W",
      "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2); RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
		"Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
	},
},
{ 
	partNo:  "GRV-IACS-24",
	features: {
		"On/off state" : true,
		"On/off latching" : false,
		"Frequency measurement" : false,
		"Period measurement" : false,
		"Pulse measurement" : false,
		"Counting / Quadrature Counting" : false,
		"Output pulsing" : false,
		"On/off totalization" : false,
		"Channel-to-channel isolation": false,
		"Number of Channels": 24,
	},
	specifications: {
	  "Nominal Input Voltage Range (RMS)": "85–140 VAC",
      "Turn-on Voltage": "85 VAC",
      "Turn-off Voltage": "35 VAC",
      "Input Impedance (± 5%)": "133 kOhms",
      "Operating Frequency": "40 Hz to 400 Hz",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "NONE",
      "Chassis Power Consumption": "1.0 W",
     "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2); RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
	  "Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
	},
},

{ 
	partNo:  "GRV-IACI-12",
	features: {
		"On/off state" : true,
		"On/off latching" : true,
		"Frequency measurement" : true,
		"Period measurement" : true,
		"Pulse measurement" : true,
		"Counting / Quadrature Counting" : true,
		"Output pulsing" : false,
		"On/off totalization" : true,
		"Channel-to-channel isolation" : true,
		"Number of Channels": 12,
	},
	specifications: {
	  "Nominal Input Voltage Range (RMS)": "85–140 VAC",
      "Turn-on Voltage": "85 VAC",
      "Turn-off Voltage": "35 VAC",
      "Input Impedance (± 5%)": "68 kOhms",
      "Operating Frequency": "40 Hz to 400 Hz",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "300 V working",
      "Chassis Power Consumption": "1.0 W",
   "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2); RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
		"Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
	},
},

{ 
	partNo:  "GRV-IACIS-12",
	features: {
		"On/off state" : true,
		"On/off latching" : false,
		"Frequency measurement" : false,
		"Period measurement" : false,
		"Pulse measurement" : false,
		"Counting / Quadrature Counting" : true,
		"Output pulsing" : false,
		"On/off totalization" : false,
		"Channel-to-channel isolation" : true,
		"Number of Channels": 12,
	},
	specifications: {
	  "Nominal Input Voltage Range (RMS)": "85–140 VAC",
      "Turn-on Voltage": "85 VAC",
      "Turn-off Voltage": "35 VAC",
      "Input Impedance (± 5%)": "68 kOhms",
      "Operating Frequency": "40 Hz to 400 Hz",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "300 V working",
      "Chassis Power Consumption": "1.0 W",
	  "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2); RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
		 "Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
	},
},
{ 
	partNo:  "GRV-IACHV-24",
	features: {
		"On/off state" : true,
		"On/off latching" : true,
		"Frequency measurement" : true,
		"Period measurement" : true,
		"Pulse measurement" : true,
		"Counting / Quadrature Counting" : true,
		"Output pulsing" : false,
		"On/off totalization" : true,
		"Channel-to-channel isolation" : false,
		"Number of Channels": 24,
	},
	specifications: {
  	  "Nominal Input Voltage Range (RMS)": "180–280 VAC",
      "Turn-on Voltage": "180 VAC",
      "Turn-off Voltage": "100 VAC",
      "Input Impedance (± 5%)": "532 kOhms",
      "Operating Frequency": "40 Hz to 400 Hz",
      "Turn-on Time (typical)": "30 ms at V",
      "Turn-off Time (typical)": "30 ms at V",
      "Isolation (field-to-logic)": "300 VAC, 1500 V Transient",
      "Isolation (channel-to-channel)": "N/A",
      "Chassis Power Consumption": "1.0 W",
      "Agency Approvals": "CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
	  "Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
	},
},

{ 
	partNo:  "GRV-IACHVS-24",
	features: {
		"On/off state" : true,
		"On/off latching" : false,
		"Frequency measurement" : false,
		"Period measurement" : false,
		"Pulse measurement" : false,
		"Counting / Quadrature Counting" : false,
		"Output pulsing" : false,
		"On/off totalization" : false,
		"Channel-to-channel isolation" : false,
		"Number of Channels": 24,
	},
	specifications: {
	  "Nominal Input Voltage Range (RMS)": "180–280 VAC",
      "Turn-on Voltage": "180 VAC",
      "Turn-off Voltage": "100 VAC",
      "Input Impedance (± 5%)": "532 kOhms",
      "Operating Frequency": "40 Hz to 400 Hz",
      "Turn-on Time (typical)": "30 ms at V",
      "Turn-off Time (typical)": "30 ms at V",
      "Isolation (field-to-logic)": "300 VAC, 1500 V Transient",
      "Isolation (channel-to-channel)": "N/A",
      "Chassis Power Consumption": "1.0 W",
      "Agency Approvals": "CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
	  "Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
	},
},

{ 
	partNo:  "GRV-IACIHV-12",
	features: {
		"On/off state" : true,
		"On/off latching" : true,
		"Frequency measurement" : true,
		"Period measurement" : true,
		"Pulse measurement" : true,
		"Counting / Quadrature Counting" : true,
		"Output pulsing" : false,
		"On/off totalization" : true,
		"Channel-to-channel isolation" : true,
		 "Number of Channels": 12,
	},
	specifications: {
	  "Nominal Input Voltage Range (RMS)": "180–280 VAC",
      "Turn-on Voltage": "180 VAC",
      "Turn-off Voltage": "100 VAC",
      "Input Impedance (± 5%)": "271 kOhms",
      "Operating Frequency": "40 Hz to 400 Hz",
      "Turn-on Time (typical)": "30 ms at V",
      "Turn-off Time (typical)": "30 ms at V",
      "Isolation (field-to-logic)": "300 VAC, 1500 V Transient",
      "Isolation (channel-to-channel)": "300 VAC working",
      "Chassis Power Consumption": "1.0 W",
	  "Agency Approvals": "CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
	  "Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
     
	},
},

{ 
	partNo:  "GRV-IACIHVS-12",
	features: {
		"On/off state" : true,
		"On/off latching" : false,
		"Frequency measurement" : false,
		"Period measurement" : false,
		"Pulse measurement" : false,
		"Counting / Quadrature Counting" : false,
		"Output pulsing" : false,
		"On/off totalization" : false,
		"Channel-to-channel isolation" : true,
		 "Number of Channels": 12,

	},
	specifications: {
	  "Nominal Input Voltage Range (RMS)": "180–280 VAC",
      "Turn-on Voltage": "180 VAC",
      "Turn-off Voltage": "100 VAC",
      "Input Impedance (± 5%)": "271 kOhms",
      "Operating Frequency": "40 Hz to 400 Hz",
      "Turn-on Time (typical)": "30 ms at V",
      "Turn-off Time (typical)": "30 ms at V",
      "Isolation (field-to-logic)": "300 VAC, 1500 V Transient",
      "Isolation (channel-to-channel)": "300 VAC working",

      "Chassis Power Consumption": "1.0 W",
      "Agency Approvals": "CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
	  "Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
      
	},
},
{ 
	partNo:  "GRV-IACDCTTL-24",
	features: {
		"On/off state" : true,
		"On/off latching" : true,
		"Frequency measurement" : true,
		"Period measurement" : true,
		"Pulse measurement" : true,
		"Counting / Quadrature Counting" : true,
		"Output pulsing" : false,
		"On/off totalization" : true,
		"Channel-to-channel isolation" : false,
		
		 "Number of Channels": 24,
	
	},
	specifications: {
	 "Input Voltage": "2–16 VAC / VDC",
      "Turn-on Voltage": "2.0 VAC (Peak) / VDC",
      "Turn-off Voltage": "0.8 VAC (Peak) / VDC",
      "Input Impedance (± 5%)": "2 kOhms",
      "Max. Freq. (50% square wave 5 Vp-p)": "2000 Hz",
      "IEC Input Type": "N/A",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "None",

      "Chassis Power Consumption": "1.0 W",
      "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
	"Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
      
	},
},

{ 
	partNo:  "GRV-IACDCTTLS-24",
	features: {
		"On/off state" : true,
		"On/off latching" : false,
		"Frequency measurement" : false,
		"Period measurement" : false,
		"Pulse measurement" : false,
		"Counting / Quadrature Counting" : true,
		"Output pulsing" : false,
		"On/off totalization" : false,
		"Channel-to-channel isolation" : false,
		
		 "Number of Channels": 24,
	},
	specifications: {
	   "Input Voltage": "2–16 VAC / VDC",
      "Turn-on Voltage": "2.0 VAC (peak) / VDC",
      "Turn-off Voltage": "0.8 VAC (Peak) / VDC",
      "Input Impedance (± 5%)": "2 kOhms",
      "Max. Freq. (50% square wave 5 Vp-p)": "N/A",
      "IEC Input Type": "N/A",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "None",

      "Chassis Power Consumption": "1.0 W",
      "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
	"Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
      
	},
},
{ 
	partNo:  "GRV-IDC-24",
	features: {
		"On/off state" : true,
		"On/off latching" : true,
		"Frequency measurement" : true,
		"Period measurement" : true,
		"Pulse measurement" : true,
		"Counting / Quadrature Counting" : true,
		"Output pulsing" : false,
		"On/off totalization" : true,
		"Channel-to-channel isolation" : false,
		
		 "Number of Channels": 24,
	},
	
	specifications: {
 "Input Voltage (VDC)": "15–30 VDC",
      "Turn ON Characteristic": "15 V, > 2 mA",
      "Turn OFF Characteristic": "5 V, < 0.5 mA",
      "Input Impedance (± 5%)": "Nonlinear per IEC input type",
      "Max. Freq. (50% square wave 24Vp-p)": "1000 Hz",
      "IEC Input Type": "Type I",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "None",

      "Chassis Power Consumption": "1.2 W",
     "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
      
	},
	mechanical: {
 "Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
      
	},
},

{ 
	partNo:  "GRV-IDCS-24",
	features: {
		"On/off state" : true,
		"On/off latching" : false,
		"Frequency measurement" : false,
		"Period measurement" : false,
		"Pulse measurement" : false,
		"Counting / Quadrature Counting" : false,
		"Output pulsing" : false,
		"On/off totalization" : false,
		"Channel-to-channel isolation" : false,
		
		 "Number of Channels": 24,
		 
	},
	
	specifications: {
 "Input Voltage (VDC)": "15–30 VDC",
      "Turn ON Characteristic": "15 V, > 2 mA",
      "Turn OFF Characteristic": "5 V, < 0.5 mA",
      "Input Impedance (± 5%)": "Nonlinear per IEC input type",
      "Max. Freq. (50% square wave 24Vp-p)": "1000 Hz",
      "IEC Input Type": "Type I",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "None",

      "Chassis Power Consumption": "1.2 W",
      "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
"Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
      
	},
},
{ 
	partNo:  "GRV-IDCI-12",
	features: {
		"On/off state" : true,
		"On/off latching" : true,
		"Frequency measurement" : true,
		"Period measurement" : true,
		"Pulse measurement" : true,
		"Counting / Quadrature Counting" : true,
		"Output pulsing" : false,
		"On/off totalization" : true,
		"Channel-to-channel isolation" : true,
		 "Number of Channels": 12,
	},
	specifications: {
	"Input Voltage (VDC)": "10–30 VDC",
      "Turn ON Characteristic": "10 V, > 2 mA",
      "Turn OFF Characteristic": "5 V, < 1.5 mA",
      "Input Impedance (± 5%)": "Nonlinear per IEC input type",
      "Max. Freq. (50% square wave 24Vp-p)": "1000 Hz",
      "IEC Input Type": "Type III",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "300 V working",

      "Chassis Power Consumption": "1.2 W",
      "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
	},
	mechanical: {
	"Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
      
	},
},
{
	partNo:  "GRV-IDCIS-12",
	features: {
		"On/off state" : true,
		"On/off latching" : false,
		"Frequency measurement" : false,
		"Period measurement" : false,
		"Pulse measurement" : false,
		"Counting / Quadrature Counting" : false,
		"Output pulsing" : false,
		"On/off totalization" : false,
		"Channel-to-channel isolation" : true,
		
		 "Number of Channels": 12,
		 
	},
	specifications: {
 "Input Voltage (VDC)": "10–30 VDC",
      "Turn ON Characteristic": "10 V, > 2 mA",
      "Turn OFF Characteristic": "5 V, < 1.5 mA",
      "Input Impedance (± 5%)": "Nonlinear per IEC input type",
      "Max. Freq. (50% square wave 24Vp-p)": "1000 Hz",
      "IEC Input Type": "Type III",
      "Isolation (field-to-logic)": "300 V working, 1500 V transient (1 minute)",
      "Isolation (channel-to-channel)": "300 V working",

      "Chassis Power Consumption": "1.2 W",
      "Agency Approvals": "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
      "Warranty": "Lifetime"
      
	},
	mechanical: {
	"Wire Size": "28–14 AWG",
      "Torque, connector screw": "2.5 in-lb (0.28 N-m)",
      "Torque, hold-down screw": "3.5 in-lb (0.4 N-m)",
      "Temperature (operating)": "-20 °C to +70 °C",
      "Temperature (storage)": "-40 °C to +85 °C",
      "Relative Humidity (non-condensing)": "5–95%",
	},
},

{
	partNo: 'GRV-ODCI-12',
	features: {
		"On/off state" : true,
		"Output pulsing" : true,
		"On/off totalization" : true,
		"Watchdog timer": true,
		"Channel-to-channel isolation" : true,
		"Quality indicator": false,
		"Number of Channels": 12, 
	},
	specifications: {	
		"Line Voltage Range (nominal)" : "5–48 VDC", 
		"Line Voltage Range (max)" : "5–60 VDC", 
		"Current Rating" : "400 mA per channel or 4.8 A per module (70 °C)", 
		"Surge Current" : "5 A peak for 1 second", 
		"Recommended Max. Fuse (fast) or Circuit Breaker" : "3 A 60 VDC / channel, 6 A 60 VDC / module", 
		"Minimum Load" : "20 mA", 
		"Output Voltage Drop" : "1.2 V max.", 
		"Off-State Leakage" : "1 mA at 60 V", 
		"Peak Blocking Voltage" : "60 V", 
		"Isolation (field-to-logic)" : "300 V working, 1500 V transient (1 minute)", 
		"Isolation (channel-to-channel)" : "300 V working, 1500 V transient (1 minute)", 
		"Chassis Power Consumption" : "1.2 W", 
		"Agency Approvals" : "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
		"Warranty" : "Lifetime",
	},
	mechanical: {
		"Wire Size" : "28–14 AWG",
		"Torque, connector screw" : "2.5 in-lb (0.28 N-m)",
		"Torque, hold-down screw" : "3.5 in-lb (0.4 N-m)",
		"Temperature (operating)" : "-20 °C to +70 °C",
		"Temperature (storage)" : "-40 °C to +85 °C",
		"Relative Humidity (non-condensing)" : "5–95%",
	}
}, 
{
	partNo: 'GRV-ODCIS-12',
	features: {
		"On/off state" : true,
		"Output pulsing" : false,
		"On/off totalization" : false,
		"Watchdog timer" : true,
		"Channel-to-channel isolation" : true,
		"Number of Channels": 12, 
	},
	specifications: {	
		"Line Voltage Range (nominal)" : "5–48 VDC", 
		"Line Voltage Range (max)" : "5–60 VDC", 
		"Current Rating" : "400 mA per channel or 4.8 A per module (70 °C)", 
		"Surge Current" : "5 A peak for 1 second", 
		"Recommended Max. Fuse (fast) or Circuit Breaker" : "3 A 60 VDC / channel, 6 A 60 VDC / module", 
		"Minimum Load" : "20 mA", 
		"Output Voltage Drop" : "1.2 V max.", 
		"Off-State Leakage" : "1 mA at 60 V", 
		"Peak Blocking Voltage" : "60 V", 
		"Isolation (field-to-logic)" : "300 V working, 1500 V transient (1 minute)", 
		"Isolation (channel-to-channel)" : "300 V working, 1500 V transient (1 minute)", 
		"Chassis Power Consumption" : "1.2 W", 
		"Agency Approvals" : "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
		"Warranty" : "Lifetime",
	},
	mechanical: {
		"Wire Size" : "28–14 AWG",
		"Torque, connector screw" : "2.5 in-lb (0.28 N-m)",
		"Torque, hold-down screw" : "3.5 in-lb (0.4 N-m)",
		"Temperature (operating)" : "-20 °C to +70 °C",
		"Temperature (storage)" : "-40 °C to +85 °C",
		"Relative Humidity (non-condensing)" : "5–95%",
	}
}, 
{
	partNo: 'GRV-ODCSRC-24',
	features: {
		"On/off state" : true,
		"Output pulsing" : false,
		"On/off totalization" : false,
		"Watchdog timer" : true,
		"Channel-to-channel isolation" : false,
		"Number of Channels" : 24,
		},
	specifications: {	
		"Line Voltage Range (nominal)" : "12–24 VDC",
		"Line Voltage Range (max)" : "5–60 VDC",
		"Current Rating (per channel)" : "0.4 A",
		"Surge Current" : "1.5 A for 1.0 Second",
		"Recommended Max. Fuse (fast) / Circuit Breaker" : "2 A, 60 VDC / channel or 20 A, 60 VDC common",
		"Minimum Load" : "5.0 mA",
		"Output Voltage Drop" : "0.3 V max. at 0.4 A",
		"Off-State Leakage (per channel)" : "<10 µA (@ 60 V, 70 °C)",
		"Peak Blocking Voltage" : "60.0 VDC",
		"Max. Operating Common Mode Voltage" : "250 V working, 1500 V transient",
		"Isolation (field-to-logic)" : "250 Vrms",
		"Isolation (channel-to-channel)" : "None",
		"Chassis Power Consumption" : "1.2 W",
		"Agency Approvals" : "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
		"Warranty" : "Lifetime",
	}, 
	mechanical: {
		"Wire Size" : "28–14 AWG",
		"Torque, connector screw" : "2.5 in-lb (0.28 N-m)",
		"Torque, hold-down screw" : "3.5 in-lb (0.4 N-m)",
		"Temperature (operating)" : "-20 °C to +70 °C",
		"Temperature (storage)" : "-40 °C to +85 °C",
		"Relative Humidity (non-condensing)" : "5–95%",
		
	}
},

{
	partNo: 'GRV-OMRIS-8',
	features: {
		"On/off state" : true,
		"Output pulsing" : false,
		"On/off totalization" : false,
		"Watchdog timer" : true,
		"Channel-to-channel isolation" : false,
		"Number of Channels" : 8,
		},
		
	specifications: {
		"Line Voltage Range (nominal)" : "0–250 VAC or 5–30 VDC",
		"Current Rating" : "5 A per channel",
		"Surge Current" : "6 A peak for 1 second",
		"Recommended Fuse / Circuit Breaker" : "5 A at 250 VAC / > 30 VDC per channel",
		"Leakage Current" : "< 2 µA @ 250 VAC",
		"Contact Resistance" : "≤100 mOhms",
		"Turn-On Time" : "8 ms",
		"Turn-Off Time" : "4 ms",
		"Operating Life (to specification)" : "Min. 30,000 cycles at max. ratings",
		"Mechanical Life" : "Min. 10,000,000 cycles",
		"Transient Clamp Holding Voltage" : "440 V",
		"Transient Clamping Voltage (max.)" : "720 V",
		"Isolation (coil-to-contact)" : "4000 VACrms 1 min., 10 mA detect/channel",
		"Isolation (channel-to-channel)" : "300 VAC operating, 1500 Vrms max.",
		"Chassis Power Consumption" : "1.4 W",
		"Agency Approvals" : "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
		"Warranty" : "30 months",
	},

	mechanical: {
		"Wire Size" : "28–14 AWG",
		"Torque, connector screw" : "2.5 in-lb (0.28 N-m)",
		"Torque, hold-down screw" : "3.5 in-lb (0.4 N-m)",
		"Temperature (operating)" : "-20 °C to +70 °C",
		"Temperature (storage)" : "-40 °C to +85 °C",
		"Relative Humidity (non-condensing)" : "5–95%",
	},
}, 

{
	partNo: 'GRV-OACI-12',
	features: {
		"On/off state" : true,
		"Output pulsing" : true,
		"On/off totalization" : true,
		"Watchdog timer" : true,
		"Channel-to-channel isolation" : true,
		
		"Number of Channels": 12, 
		
	},
	specifications: {	
		"Line Voltage": "12–250 VAC",
		"Current Rating": "0.5 A",
		"Recommended Max. Fuse (fast) or Circuit Breaker" : "2 A 250 VAC / channel, 6 A 250 VAC common",
		"Minimum Load Current" : "20 mA",
		"Output Voltage Drop" : "1 V",
		"Off-state Leakage at Nominal Voltage" : "1.25 mA @240 VAC 0.7 mA @ 120 VAC",
		"Peak Blocking Voltage" : "500 V",
		"Leakage (mA @ 240 V, 60 Hz)" : "1.0",
		"Operating Frequency" : "40 to 60 Hz",
		"Turn-on Time" : "≤ 1/2 cycle (zero crossing)",
		"Turn-off Time" : "≤ 1/2 cycle (zero crossing)",
		"Problem Indication" : "open circuit",
		"Isolation (field-to-logic)" : "300 V working",
		"Isolation (channel-to-channel)" : "300 V working",
		"Chassis Power Consumption" : "1.3 W",
		"Agency Approvals" : "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
		"Warranty" : "Lifetime",
	}, 
	mechanical: {
		"Wire Size" : "28–14 AWG",
		"Torque, connector screw" : "2.5 in-lb (0.28 N-m)",
		"Torque, hold-down screw" : "3.5 in-lb (0.4 N-m)",
		"Temperature (operating)" : "-20 °C to +70 °C",
		"Temperature (storage)" : "-40 °C to +85 °C",
		"Relative Humidity (non-condensing)" : "5–95%",
	},
}, 

{
	partNo: 'GRV-OACIS-12',
	features: {
		"On/off state" : true,
		"Output pulsing" : false,
		"On/off totalization" : false,
		"Watchdog timer" : true,
		"Channel-to-channel isolation" : true,
		
		"Number of Channels": 12, 
	},
	specifications: {	
		"Line Voltage": "12–250 VAC",
		"Current Rating": "0.5 A",
		"Recommended Max. Fuse (fast) or Circuit Breaker" : "2 A 250 VAC / channel, 6 A 250 VAC common",
		"Minimum Load Current" : "20 mA",
		"Output Voltage Drop" : "1 V",
		"Off-state Leakage at Nominal Voltage" : "1.25 mA @240 VAC 0.7 mA @ 120 VAC",
		"Peak Blocking Voltage" : "500 V",
		"Leakage (mA @ 240 V, 60 Hz)" : "1.0",
		"Operating Frequency" : "40 to 60 Hz, 400 Hz",
		"Turn-on Time" : "≤ 1/2 cycle (zero crossing)",
		"Turn-off Time" : "≤ 1/2 cycle (zero crossing)",
		"Problem Indication" : "none",
		"Isolation (field-to-logic)" : "300 V working",
		"Isolation (channel-to-channel)" : "300 V working",
		"Chassis Power Consumption" : "1.3 W",
		"Agency Approvals" : "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
		"Warranty" : "Lifetime",
	},
	mechanical: {
		"Wire Size" : "28–14 AWG",
		"Torque, connector screw" : "2.5 in-lb (0.28 N-m)",
		"Torque, hold-down screw" : "3.5 in-lb (0.4 N-m)",
		"Temperature (operating)" : "-20 °C to +70 °C",
		"Temperature (storage)" : "-40 °C to +85 °C",
		"Relative Humidity (non-condensing)" : "5–95%",
	},
}, 

{
	partNo: 'GRV-OAC-12',
	features: {
		"On/off state" : true,
		"Output pulsing" : true,
		"On/off totalization" : true,
		"Watchdog timer" : true,
		"Channel-to-channel isolation" : false,
		"Number of Channels": 12, 
	},
	specifications: {	
		"Line Voltage": "12–250 VAC",
		"Current Rating": "0.5 A",
		"Recommended Max. Fuse (fast) or Circuit Breaker" : "2 A 250 VAC / channel, 6 A 250 VAC common",
		"Minimum Load Current" : "20 mA",
		"Output Voltage Drop" : "1 V",
		"Off-state Leakage at Nominal Voltage" : "1.25 mA @240 VAC 0.7 mA @ 120 VAC",
		"Peak Blocking Voltage" : "500 V",
		"Leakage (mA @ 240 V, 60 Hz)" : "1.0",
		"Operating Frequency" : "40 to 60 Hz, 400 Hz",
		"Turn-on Time" : "≤ 1/2 cycle (zero crossing)",
		"Turn-off Time" : "≤ 1/2 cycle (zero crossing)",
		"Problem Indication" : "Open circuit",
		"Isolation (field-to-logic)" : "300 V working",
		"Isolation (channel-to-channel)" : "none",
		"Chassis Power Consumption" : "1.3 W",
		"Agency Approvals" : "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
		"Warranty" : "Lifetime",
	}, 
	mechanical: {
		"Wire Size" : "28–14 AWG",
		"Torque, connector screw" : "2.5 in-lb (0.28 N-m)",
		"Torque, hold-down screw" : "3.5 in-lb (0.4 N-m)",
		"Temperature (operating)" : "-20 °C to +70 °C",
		"Temperature (storage)" : "-40 °C to +85 °C",
		"Relative Humidity (non-condensing)" : "5–95%",
		
	},
},

{
	partNo: 'GRV-OACS-12',
	features: {
		
		"On/off state" : true,
		"Output pulsing" : false,
		"On/off totalization" : false,
		"Watchdog timer" : true,
		"Channel-to-channel isolation" : false,
		"Number of Channels": 12, 

	},
	specifications: {	
		"Line Voltage": "12–250 VAC",
		"Current Rating": "0.5 A",
		"Recommended Max. Fuse (fast) or Circuit Breaker" : "2 A 250 VAC / channel, 6 A 250 VAC common",
		"Minimum Load Current" : "20 mA",
		"Output Voltage Drop" : "1 V",
		"Off-state Leakage at Nominal Voltage" : "1.25 mA @240 VAC 0.7 mA @ 120 VAC",
		"Peak Blocking Voltage" : "500 V",
		"Leakage (mA @ 240 V, 60 Hz)" : "1.0",
		"Operating Frequency" : "40 to 60 Hz, 400 Hz",
		"Turn-on Time" : "≤ 1/2 cycle (zero crossing)",
		"Turn-off Time" : "≤ 1/2 cycle (zero crossing)",
		"Problem Indication" : "none",
		"Isolation (field-to-logic)" : "300 V working",
		"Isolation (channel-to-channel)" : "none",
		"Chassis Power Consumption" : "1.3 W",
		"Agency Approvals" : "UL/cUL(Class 1 Div. 2); CE, ATEX(Category 3, Zone 2), RoHS; DFARS; CB Scheme",
		"Warranty" : "Lifetime",
	}, 
	mechanical: {
		"Wire Size" : "28–14 AWG",
		"Torque, connector screw" : "2.5 in-lb (0.28 N-m)",
		"Torque, hold-down screw" : "3.5 in-lb (0.4 N-m)",
		"Temperature (operating)" : "-20 °C to +70 °C",
		"Temperature (storage)" : "-40 °C to +85 °C",
		"Relative Humidity (non-condensing)" : "5–95%",
		
	},
}
];
